backend:
  name: github
  repo: titlisen/pinwander
  branch: main
  base_url: https://tranquil-cranachan-89b19d.netlify.app

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "tours"
    label: "Tours"
    folder: "content/tours"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
